### ISSUE TITLE
TB3 does not exist anymore

### ISSUE THREAD

**Issue by pierr3** [VATFrance/France-Ground-Layouts#23]
![image](https://user-images.githubusercontent.com/1833515/92162862-1ddd3300-ee33-11ea-8e44-b06c8f8bf10c.png)
![image](https://i.imgur.com/kIxk9tg.png)

**Comment by Iwhite67** [comment]
Jepessen 7 Aout 2020

![image](https://user-images.githubusercontent.com/9698964/92163281-b378c280-ee33-11ea-98de-a42c63bf0019.png)

**Comment by Iwhite67** [comment]
https://www.sia.aviation-civile.gouv.fr/pub/media/store/documents/file/l/f/lf_sup_2020_166_fr.pdf

**Comment by pierr3** [comment]
SIA mistake, no need to change
